version: "3"

services:
  server:
    build:
      context: ./app
      target: builder
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    # command: ["/bin/sh"]  # DockerfileのCMDを上書きし、ttyを有効化
    # tty: true
